import { Request, Response } from "express"
import prisma from "../lip/prisma"

export const createClassroom = async (req: Request, res: Response) => { try { const { name, section, grade, teacherId } = req.body; if (!name || !section || !Number.isInteger(Number(grade)) || !teacherId) return res.status(400).json({ message: "Name, section, grade and teacherId are required" }); res.status(201).json(await prisma.classroom.create({ data: { name, section, grade: Number(grade), teacherId } })) } catch { res.status(500).json({ message: "Failed to create classroom" }) } }
export const getClassrooms = async (_req: Request, res: Response) => { try { res.json({ result: await prisma.classroom.findMany({ include: { teacher: true, students: { include: { student: true } } } }) }) } catch { res.status(500).json({ message: "Failed to get classrooms" }) } }
export const getClassroom = async (req: Request, res: Response) => { try { const classroom = await prisma.classroom.findUnique({ where: { id: String(req.params.id) }, include: { teacher: true, students: { include: { student: true } } } }); if (!classroom) return res.status(404).json({ message: "Classroom not found" }); res.json(classroom) } catch { res.status(500).json({ message: "Failed to get classroom" }) } }
export const updateClassroom = async (req: Request, res: Response) => { try { const { name, section, grade, teacherId } = req.body; res.json(await prisma.classroom.update({ where: { id: String(req.params.id) }, data: { ...(name !== undefined ? { name } : {}), ...(section !== undefined ? { section } : {}), ...(grade !== undefined ? { grade: Number(grade) } : {}), ...(teacherId !== undefined ? { teacherId } : {}) } })) } catch { res.status(500).json({ message: "Failed to update classroom" }) } }
export const deleteClassroom = async (req: Request, res: Response) => { try { await prisma.classroom.delete({ where: { id: String(req.params.id) } }); res.json({ message: "Classroom deleted successfully" }) } catch { res.status(500).json({ message: "Failed to delete classroom" }) } }
export const assignStudentToClassroom = async (req: Request, res: Response) => { try { const { classroomId, studentId } = req.body; res.status(201).json(await prisma.classroomStudent.upsert({ where: { classroomId_studentId: { classroomId, studentId } }, update: {}, create: { classroomId, studentId } })) } catch { res.status(500).json({ message: "Failed to assign student" }) } }
export const removeStudentFromClassroom = async (req: Request, res: Response) => { try { const { classroomId, studentId } = req.body; await prisma.classroomStudent.delete({ where: { classroomId_studentId: { classroomId, studentId } } }); res.json({ message: "Student removed successfully" }) } catch { res.status(500).json({ message: "Failed to remove student" }) } }
