ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'User';

ALTER TABLE "Teacher" ADD COLUMN IF NOT EXISTS "password" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Student" ADD COLUMN IF NOT EXISTS "password" TEXT NOT NULL DEFAULT '';
