import { Router } from "express";
import { createStudent, deleteStudent, getStudent, getStudentOverview, getStudents, studentLogin, updateStudent } from "../controller/student-controller";
import { requireDashboardAccess, requireOwnStudent, requireStudent, verifyToken } from "../middelwere/auth";
const router = Router();
router.post("/", createStudent); 
router.post("/login", studentLogin);
router.get("/", getStudents);
router.get("/:id/overview", verifyToken, requireDashboardAccess, getStudentOverview);
 router.get("/:id", verifyToken, requireStudent, requireOwnStudent, getStudent); 
 router.patch("/:id", updateStudent); 
 router.delete("/:id", deleteStudent);
export default router;
