import { Router } from "express";
import { createTeacher, deleteTeacher, getAllTeachers, getTeacher, loginTeacher, updateTeacher } from "../controller/teacher-controller";
const router = Router();
router.post("/", createTeacher); 
router.post("/login", loginTeacher);
router.get("/", getAllTeachers); 
router.get("/:id", getTeacher); 
router.patch("/:id", updateTeacher); 
router.delete("/:id", deleteTeacher);
export default router;
